
CREATE TABLE questions(
    id SERIAL,
    userid INTEGER,
    datecriation DATE,
    q1 INTEGER,
    q2 INTEGER,
    q3 INTEGER,
    q4 INTEGER,
    q5 INTEGER,
    q6 INTEGER,
    q7 INTEGER,
    q8 INTEGER,
    q9 INTEGER,
    q10 INTEGER,
    q11 INTEGER,
    q12 INTEGER,
    q13 INTEGER,
    q14 INTEGER,
    q15 INTEGER,
    q16 INTEGER,
    q17 INTEGER,
    q18 INTEGER,
    q19 INTEGER,
    q20 INTEGER,
    q21 INTEGER,
    q22 INTEGER,
    q23 INTEGER,
    q24 INTEGER,
    q25 INTEGER,
    q26 INTEGER,
    q27 INTEGER,
    q28 INTEGER,
    q29 INTEGER,
    total FLOAT,
    CONSTRAINT questions_id_pk PRIMARY KEY (id)
);
